name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test

    - name: Generate coverage report
      run: npm run test:coverage

    - name: Upload coverage report to Codeclimate
      uses: Brightspace/code-coverage-action@v2
      with:
        code-coverage-report-path: ./coverage/lcov.info
        code-coverage-source: lcov

    - name: Display test coverage
      run: cat ./coverage/lcov.info | npx coveralls